drop extension if exists "pg_net";

create sequence "public"."tmplist_items_id_seq";


  create table "public"."chat_links" (
    "id" uuid not null default gen_random_uuid(),
    "chat_id" bigint not null,
    "created_by" bigint,
    "created_at" timestamp with time zone default now(),
    "expires_at" timestamp with time zone,
    "is_active" boolean default true,
    "message_id" bigint,
    "name" text
      );


alter table "public"."chat_links" enable row level security;


  create table "public"."members" (
    "id" bigint generated by default as identity not null,
    "username" text not null,
    "full_name" text,
    "external_name" text,
    "created_at" timestamp without time zone default now(),
    "chat_id" bigint,
    "user_id" bigint,
    "extra_role" text
      );


alter table "public"."members" enable row level security;


  create table "public"."tmplist_items" (
    "id" bigint not null default nextval('public.tmplist_items_id_seq'::regclass),
    "tmplist_id" uuid,
    "user_id" bigint not null
      );


alter table "public"."tmplist_items" enable row level security;


  create table "public"."tmplists" (
    "id" uuid not null default gen_random_uuid(),
    "chat_id" bigint not null,
    "created_by" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "expires_at" timestamp with time zone not null,
    "message_id" bigint,
    "is_active" boolean not null default true,
    "name" text not null
      );


alter table "public"."tmplists" enable row level security;

alter sequence "public"."tmplist_items_id_seq" owned by "public"."tmplist_items"."id";

CREATE UNIQUE INDEX chat_links_pkey ON public.chat_links USING btree (id);

CREATE UNIQUE INDEX members_chat_user_unique ON public.members USING btree (chat_id, user_id);

CREATE UNIQUE INDEX members_pkey ON public.members USING btree (id);

CREATE UNIQUE INDEX tmplist_items_pkey ON public.tmplist_items USING btree (id);

CREATE UNIQUE INDEX tmplist_items_unique ON public.tmplist_items USING btree (tmplist_id, user_id);

CREATE UNIQUE INDEX tmplists_pkey ON public.tmplists USING btree (id);

CREATE UNIQUE INDEX uniq_tmplist_user ON public.tmplist_items USING btree (tmplist_id, user_id);

alter table "public"."chat_links" add constraint "chat_links_pkey" PRIMARY KEY using index "chat_links_pkey";

alter table "public"."members" add constraint "members_pkey" PRIMARY KEY using index "members_pkey";

alter table "public"."tmplist_items" add constraint "tmplist_items_pkey" PRIMARY KEY using index "tmplist_items_pkey";

alter table "public"."tmplists" add constraint "tmplists_pkey" PRIMARY KEY using index "tmplists_pkey";

alter table "public"."members" add constraint "members_chat_user_unique" UNIQUE using index "members_chat_user_unique";

alter table "public"."tmplist_items" add constraint "tmplist_items_tmplist_id_fkey" FOREIGN KEY (tmplist_id) REFERENCES public.tmplists(id) ON DELETE CASCADE not valid;

alter table "public"."tmplist_items" validate constraint "tmplist_items_tmplist_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.members_for_token(p_token uuid)
 RETURNS TABLE(id bigint, username text, full_name text, external_name text, extra_role text)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_chat_id bigint;
begin
  select cl.chat_id
    into v_chat_id
  from public.chat_links cl
  where cl.id = p_token
    and cl.is_active = true
    and (cl.expires_at is null or cl.expires_at > now())
  limit 1;

  if v_chat_id is null then
    return;
  end if;

  return query
  select
    m.id,
    m.username,
    m.full_name,
    m.external_name,
    m.extra_role
  from public.members m
  where m.chat_id = v_chat_id
  order by m.id asc;
end;
$function$
;

grant delete on table "public"."chat_links" to "anon";

grant insert on table "public"."chat_links" to "anon";

grant references on table "public"."chat_links" to "anon";

grant select on table "public"."chat_links" to "anon";

grant trigger on table "public"."chat_links" to "anon";

grant truncate on table "public"."chat_links" to "anon";

grant update on table "public"."chat_links" to "anon";

grant delete on table "public"."chat_links" to "authenticated";

grant insert on table "public"."chat_links" to "authenticated";

grant references on table "public"."chat_links" to "authenticated";

grant select on table "public"."chat_links" to "authenticated";

grant trigger on table "public"."chat_links" to "authenticated";

grant truncate on table "public"."chat_links" to "authenticated";

grant update on table "public"."chat_links" to "authenticated";

grant delete on table "public"."chat_links" to "service_role";

grant insert on table "public"."chat_links" to "service_role";

grant references on table "public"."chat_links" to "service_role";

grant select on table "public"."chat_links" to "service_role";

grant trigger on table "public"."chat_links" to "service_role";

grant truncate on table "public"."chat_links" to "service_role";

grant update on table "public"."chat_links" to "service_role";

grant delete on table "public"."members" to "anon";

grant insert on table "public"."members" to "anon";

grant references on table "public"."members" to "anon";

grant select on table "public"."members" to "anon";

grant trigger on table "public"."members" to "anon";

grant truncate on table "public"."members" to "anon";

grant update on table "public"."members" to "anon";

grant delete on table "public"."members" to "authenticated";

grant insert on table "public"."members" to "authenticated";

grant references on table "public"."members" to "authenticated";

grant select on table "public"."members" to "authenticated";

grant trigger on table "public"."members" to "authenticated";

grant truncate on table "public"."members" to "authenticated";

grant update on table "public"."members" to "authenticated";

grant delete on table "public"."members" to "service_role";

grant insert on table "public"."members" to "service_role";

grant references on table "public"."members" to "service_role";

grant select on table "public"."members" to "service_role";

grant trigger on table "public"."members" to "service_role";

grant truncate on table "public"."members" to "service_role";

grant update on table "public"."members" to "service_role";

grant delete on table "public"."tmplist_items" to "anon";

grant insert on table "public"."tmplist_items" to "anon";

grant references on table "public"."tmplist_items" to "anon";

grant select on table "public"."tmplist_items" to "anon";

grant trigger on table "public"."tmplist_items" to "anon";

grant truncate on table "public"."tmplist_items" to "anon";

grant update on table "public"."tmplist_items" to "anon";

grant delete on table "public"."tmplist_items" to "authenticated";

grant insert on table "public"."tmplist_items" to "authenticated";

grant references on table "public"."tmplist_items" to "authenticated";

grant select on table "public"."tmplist_items" to "authenticated";

grant trigger on table "public"."tmplist_items" to "authenticated";

grant truncate on table "public"."tmplist_items" to "authenticated";

grant update on table "public"."tmplist_items" to "authenticated";

grant delete on table "public"."tmplist_items" to "service_role";

grant insert on table "public"."tmplist_items" to "service_role";

grant references on table "public"."tmplist_items" to "service_role";

grant select on table "public"."tmplist_items" to "service_role";

grant trigger on table "public"."tmplist_items" to "service_role";

grant truncate on table "public"."tmplist_items" to "service_role";

grant update on table "public"."tmplist_items" to "service_role";

grant delete on table "public"."tmplists" to "anon";

grant insert on table "public"."tmplists" to "anon";

grant references on table "public"."tmplists" to "anon";

grant select on table "public"."tmplists" to "anon";

grant trigger on table "public"."tmplists" to "anon";

grant truncate on table "public"."tmplists" to "anon";

grant update on table "public"."tmplists" to "anon";

grant delete on table "public"."tmplists" to "authenticated";

grant insert on table "public"."tmplists" to "authenticated";

grant references on table "public"."tmplists" to "authenticated";

grant select on table "public"."tmplists" to "authenticated";

grant trigger on table "public"."tmplists" to "authenticated";

grant truncate on table "public"."tmplists" to "authenticated";

grant update on table "public"."tmplists" to "authenticated";

grant delete on table "public"."tmplists" to "service_role";

grant insert on table "public"."tmplists" to "service_role";

grant references on table "public"."tmplists" to "service_role";

grant select on table "public"."tmplists" to "service_role";

grant trigger on table "public"."tmplists" to "service_role";

grant truncate on table "public"."tmplists" to "service_role";

grant update on table "public"."tmplists" to "service_role";

grant execute on function public.members_for_token(uuid) to anon;

