


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."members_for_token"("p_token" "uuid") RETURNS TABLE("id" bigint, "username" "text", "full_name" "text", "external_name" "text", "extra_role" "text")
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
declare
  v_chat_id bigint;
begin
  -- 1️⃣ Проверяем токен и получаем chat_id
  select cl.chat_id
    into v_chat_id
  from public.chat_links cl
  where cl.id = p_token
    and cl.is_active = true
    and (cl.expires_at is null or cl.expires_at > now())
  limit 1;

  -- 2️⃣ Если токен невалидный → ничего не возвращаем
  if v_chat_id is null then
    return;
  end if;

  -- 3️⃣ Возвращаем участников
  return query
  select
    m.id,
    m.username,
    m.full_name,
    m.external_name,
    m.extra_role
  from public.members m
  where m.chat_id = v_chat_id
  order by m.id asc;
end;
$$;


ALTER FUNCTION "public"."members_for_token"("p_token" "uuid") OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."chat_links" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "chat_id" bigint NOT NULL,
    "created_by" bigint,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "expires_at" timestamp with time zone,
    "is_active" boolean DEFAULT true,
    "message_id" bigint,
    "name" "text"
);


ALTER TABLE "public"."chat_links" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."members" (
    "id" bigint NOT NULL,
    "username" "text" NOT NULL,
    "full_name" "text",
    "external_name" "text",
    "created_at" timestamp without time zone DEFAULT "now"(),
    "chat_id" bigint,
    "user_id" bigint,
    "extra_role" "text"
);


ALTER TABLE "public"."members" OWNER TO "postgres";


ALTER TABLE "public"."members" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."members_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."tmplist_items" (
    "id" bigint NOT NULL,
    "tmplist_id" "uuid",
    "user_id" bigint NOT NULL
);


ALTER TABLE "public"."tmplist_items" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."tmplist_items_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."tmplist_items_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."tmplist_items_id_seq" OWNED BY "public"."tmplist_items"."id";



CREATE TABLE IF NOT EXISTS "public"."tmplists" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "chat_id" bigint NOT NULL,
    "created_by" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "expires_at" timestamp with time zone NOT NULL,
    "message_id" bigint,
    "is_active" boolean DEFAULT true NOT NULL,
    "name" "text" NOT NULL
);


ALTER TABLE "public"."tmplists" OWNER TO "postgres";


ALTER TABLE ONLY "public"."tmplist_items" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."tmplist_items_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."chat_links"
    ADD CONSTRAINT "chat_links_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."members"
    ADD CONSTRAINT "members_chat_user_unique" UNIQUE ("chat_id", "user_id");



ALTER TABLE ONLY "public"."members"
    ADD CONSTRAINT "members_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tmplist_items"
    ADD CONSTRAINT "tmplist_items_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tmplists"
    ADD CONSTRAINT "tmplists_pkey" PRIMARY KEY ("id");



CREATE UNIQUE INDEX "tmplist_items_unique" ON "public"."tmplist_items" USING "btree" ("tmplist_id", "user_id");



CREATE UNIQUE INDEX "uniq_tmplist_user" ON "public"."tmplist_items" USING "btree" ("tmplist_id", "user_id");



ALTER TABLE ONLY "public"."tmplist_items"
    ADD CONSTRAINT "tmplist_items_tmplist_id_fkey" FOREIGN KEY ("tmplist_id") REFERENCES "public"."tmplists"("id") ON DELETE CASCADE;



ALTER TABLE "public"."chat_links" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."members" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."tmplist_items" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."tmplists" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."members_for_token"("p_token" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."members_for_token"("p_token" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."members_for_token"("p_token" "uuid") TO "service_role";


















GRANT ALL ON TABLE "public"."chat_links" TO "anon";
GRANT ALL ON TABLE "public"."chat_links" TO "authenticated";
GRANT ALL ON TABLE "public"."chat_links" TO "service_role";



GRANT ALL ON TABLE "public"."members" TO "anon";
GRANT ALL ON TABLE "public"."members" TO "authenticated";
GRANT ALL ON TABLE "public"."members" TO "service_role";



GRANT ALL ON SEQUENCE "public"."members_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."members_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."members_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."tmplist_items" TO "anon";
GRANT ALL ON TABLE "public"."tmplist_items" TO "authenticated";
GRANT ALL ON TABLE "public"."tmplist_items" TO "service_role";



GRANT ALL ON SEQUENCE "public"."tmplist_items_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tmplist_items_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tmplist_items_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."tmplists" TO "anon";
GRANT ALL ON TABLE "public"."tmplists" TO "authenticated";
GRANT ALL ON TABLE "public"."tmplists" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";


